### ISSUE TITLE
ckeditor striping html classes

### ISSUE THREAD

**Issue by swilla** [Laravel-Backpack/PageManager#10]
Is there a way to modify the config for the ckeditor?  It's removing the classes when I edit a page.

**Comment by tabacitu** [comment]
Hi @swilla ,

You should be able to make any configurations you'd like in ```public/vendor/backpack/ckeditor/config.js```. It might take some hard refreshes or cache-emptying to actually be applied, though. Best to try it out in an Incognito Tab.

Cheers!

**Comment by Justproof** [comment]
My install is missing  /vendor/backpack/ckeditor/config.js 
There are 4 folders within /vendor backpack " base  crud  generators  pagemanager"

**Comment by neoplomero** [comment]
@tabacitu Why is this closed? there's no such a file.

**Comment by danielwaghorn** [comment]
For anyone who comes across this looking for a solution, edit `public/vendor/backpack/ckeditor/config.js`, and add the following to `CKEDITOR.editorConfig`:

```
	// Prevent tampering with source
	config.allowedContent = true;
```

**Comment by tabacitu** [comment]
Thanks for sharing your solution @danielwaghorn ! Even if you don't get a thanks right away - I guarantee someone someday will have the same need as you, and they'll be grateful to you :-)

Cheers!
