### ISSUE TITLE
Target class [PageController] does not exist.

### ISSUE THREAD

**Issue by vonsogt** [Laravel-Backpack/PageManager#100]
# Bug report

### What I did:
After installed until the "Example front-end" then I try to add the route in `routes/backpack/custom.php` and I tried to make a new page and accessing it and show that error

### What I expected to happen:
The Page will created from admin

### What happened:
I got this error:
`Target class [PageController] does not exist.`

### What I've already tried to fix it:
Recreate the routes and test in web.php too

### Backpack, Laravel, PHP, DB version:
Backpack : 4.x.x
Laravel: 6.x.x
PHP : 7.2.x
DB : mysql

**Comment by vonsogt** [comment]
Fixed by changing the controller at routes:
from:
```
Route::get('{page}/{subs?}', ['uses' => 'PageController@index'])
    ->where(['page' => '^(((?=(?!admin))(?=(?!\/)).))*$', 'subs' => '.*']);
```

to:
```
Route::get('{page}/{subs?}', ['uses' => '\App\Http\Controllers\PageController@index'])
    ->where(['page' => '^(((?=(?!admin))(?=(?!\/)).))*$', 'subs' => '.*']);
```

**Comment by tabacitu** [comment]
Thank you @vonsogt . I've just changed the README file to reflect your change. That's indeed better in most use cases. Cheers!

**Comment by kingofwa** [comment]
thank you verrymuch
