### ISSUE TITLE
Error : Declaration of ... Page::sluggable() must be compatible with Cviebrock\EloquentSluggable\Sluggable::sluggable(): array

### ISSUE THREAD

**Issue by mansourcodes** [Laravel-Backpack/PageManager#111]
# Bug report

`Declaration of Backpack\PageManager\app\Models\Page::sluggable() must be compatible with Cviebrock\EloquentSluggable\Sluggable::sluggable(): array`

see: https://flareapp.io/share/95JXGlLP#F1

### What I did:
install  PageManager on new backpack insulation with Laravel 8
using these steps https://github.com/Laravel-Backpack/PageManager

after clicking the side menu item  this error shows

**Comment by mansourcodes** [comment]
### Fixed

add `: array` to Backpack\PageManager\app\Models\Page::sluggable()

```
    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'slug_or_title',
            ],
        ];
    }
```

**Comment by promatik** [comment]
@mansourcodes thank you for this report, there's already an open pull request to cover this issue; https://github.com/Laravel-Backpack/PageManager/pull/110
I'll close this one for now.

**Comment by MohsenRajabi** [comment]
**مشکل حل شد ممنونم.**

> ### Fixed
> add `: array` to Backpack\PageManager\app\Models\Page::sluggable()
> 
> ```
>     /**
>      * Return the sluggable configuration array for this model.
>      *
>      * @return array
>      */
>     public function sluggable(): array
>     {
>         return [
>             'slug' => [
>                 'source' => 'slug_or_title',
>             ],
>         ];
>     }
> ```
