### ISSUE TITLE
create page an show me on the front end!

### ISSUE THREAD

**Issue by deyvsonaguiar** [Laravel-Backpack/PageManager#12]
how I create my page and show on the front end after creating it in the laravel pack back-end?

**Comment by michaellindahl** [comment]
Laravel Backpack is a collection of packages for a backend admin panel. PageManager adds pages to that mix. Backpack is not intended to be a front end solution, however the readme shows an example of how you could add a controller to serve pages: https://github.com/Laravel-Backpack/PageManager#example-front-end

 Could you clarify the issue you are encountering?

**Comment by deyvsonaguiar** [comment]
I don't understant this example here... sorry

**Comment by tabacitu** [comment]
Hi @deyvsonaguiar ,

Using Backpack can be quite frustrating if you're just starting out using Laravel. But I'm afraid the PageManager example is as simple as it can get. 

I recommend you start out by going through Jeffrey Way's excellent [Laravel from scratch](https://laracasts.com/series/laravel-5-from-scratch) series. You'll most definitely understand afterwards.

Cheers!

**Comment by josefanderson215** [comment]
Hi, deyvsonaguiar
How are you!
I am going to use the PageManager.
Can you help me?
I have some problem.
How to build the UI (Frond End) of project?
As you can know, backend is done but front end have to build.
Please help!!!
