### ISSUE TITLE
support for translation / multiple language

### ISSUE THREAD

**Issue by KeldNielsen86** [Laravel-Backpack/PageManager#129]
A feature I would like to have in this plugin is that I will be able to add my page in different language, in case the webpage need to be exposed to different countries. 

it would be nice if the pagemanager read the  'locale' => 'en', variable and showed the page matching the language.

**Comment by tabacitu** [comment]
Hey @KeldNielsen86 ,

We do not plan on adding multi-language support to PageManager, sorry. It can't be done as a clean non-breaking change: for most websites it doesn't make sense, and it would just bloat those projects, for a few projects that do need it. 

We might, however, create a different add-on for that, something like TranslatablePageManager. Please subscribe to our blog digest on backpackforlaravel.com to find out if/when we do.

Until then, if you need that, I recommend you copy-paste the code from this PageManager to your own app and change the namespaces. It should "_just work_", and you'll be able to make the Page entity translatable in your own project. Keep in mind that this repo won't receive many updates anyway, so it's not like you're losing out or something, it's perfectly fine to copy-paste it in your app.

Hope it helps.
Cheers!

**Comment by KeldNielsen86** [comment]
thank you for the answer. however, Ido hope that you will consider making the Translate module someday. I will sign up for newsletters :)

**Comment by SequelONE** [comment]
Do you have any ideas how to implement this? We really need multilingual support in PageManager.

**Comment by pxpm** [comment]
Hello @SequelONE 
You should extend the permission manager crud controller by binding your own controller with translations. Or moving the package to your app, removing the package and doing your needed changes.
Cheers

**Comment by SequelONE** [comment]
Thank you @pxpm
