### ISSUE TITLE
Is there any way to access template's information from Page Controller?

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/PageManager#13]
I want to add photo galleries to pages by using a custom template and i would need to know, for example, how to read the disk that is associated with the field that contains the images in order to be able to delete those files when i want.

**Comment by tabacitu** [comment]
Hi @AurelDragut ,

Sure, your PageController should look something like this:
```php

namespace App\Http\Controllers;

use Backpack\PageManager\app\Models\Page;

class PageController extends Controller
{
    public function index($slug_or_id)
    {
        $page = Page::findBySlug($slug_or_id);

        if (!$page)
        {
            abort(404, 'Please go back to our <a href="'.url('').'">homepage</a>.');
        }

        $this->data['title'] = $page->title;
        $this->data['page'] = $page->withFakes();

        return view('pages.'.$page->template, $this->data);
    }
}
```

And ```$page->template``` should contain all the information you need.

**Comment by tabacitu** [comment]
P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.
