### ISSUE TITLE
Nested pages?

### ISSUE THREAD

**Issue by adrienne** [Laravel-Backpack/PageManager#131]
Is there any way to make nested pages (pages with a parent page) work in PageManager?

**Comment by karandatwani92** [comment]
Hello @adrienne

Do you want your page view to open inside a parent layout?
For that, You are free to extend any parent layout for your page using `@extends('parent_view')`

Let me know what you mean by this is something else.

**Comment by karandatwani92** [comment]
Hi @adrienne
Got your point, It's related to the `route` in `web.php`. We'll try to come up with a more generic solution.

But for now, you can define a route in this **order** as per your need:
```php
Route::get('about-us/{page}/{subs?}', ['uses' => '\App\Http\Controllers\PageController@index'])
    ->where(['page' => '^(((?=(?!admin))(?=(?!\/)).))*$', 'subs' => '.*']);

//this would be last one
Route::get('{page}/{subs?}', ['uses' => '\App\Http\Controllers\PageController@index'])
    ->where(['page' => '^(((?=(?!admin))(?=(?!\/)).))*$', 'subs' => '.*']);
```

and in page manager, your slug would be `team`

**Comment by adrienne** [comment]
Yeah, that's still not what I'm asking, but it's okay, I found a different package to use.

**Comment by karandatwani92** [comment]
@adrienne can you share the package link..so we could understand the implementation you want.
