### ISSUE TITLE
Unknown database type bit requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it.

### ISSUE THREAD

**Issue by webdesign7** [Laravel-Backpack/PageManager#138]
# Bug report

### What I did:

Fresh installation: Backpack 6, Laravel 10  etc 

### What I expected to happen:
Open page manager `http://localhost/admin/page/create` 

### What happened: 
Unknown database type bit requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it.

### Backpack, Laravel, PHP, DB version:
Backpack 6, Laravel 10, PHP 8.2.7 , DB  mysql 8

**Comment by webdesign7** [comment]
![Screenshot 2023-11-26 at 10 36 05](https://github.com/Laravel-Backpack/PageManager/assets/2030016/d56dd3c7-2aff-4817-a6d6-a99f04204d23)
To give more details

**Comment by webdesign7** [comment]
Thanks for your reply ! but I am confused 

When I comment  these fields  in app/PageTemplate.php then it works : 

`$this->crud->addField([
            'name' => 'meta_title',
            'label' => trans('backpack::pagemanager.meta_title'),
            'fake' => true,
            'store_in' => 'extras',
        ]);
        $this->crud->addField([
            'name' => 'meta_description',
            'label' => trans('backpack::pagemanager.meta_description'),
            'fake' => true,
            'store_in' => 'extras',
        ]);`

also I can't see any column type defined as `bit`  where can I find that to change ?  

As per new Laravel 10  dockerised installation it used Mysql 8

**Comment by pxpm** [comment]
You are welcome. I am confused too, why removing those fields would fix the issue. 

Yes, they store json in a text column: https://github.com/Laravel-Backpack/PageManager/blob/92910a9b6895498e2b9078343f5dfa6eb9143fda/src/database/migrations/2016_05_25_121918_create_pages_table.php#L23

But AFAIK there is no issue in mysql 8 and those fields, I am using mysql 8 myself
![image](https://github.com/Laravel-Backpack/PageManager/assets/7188159/1e740856-ddd1-4f92-a777-fc3036dc3b99)

Could it be some specific installation setting ? Do you have a chance to test it in other environment? Maybe a quick https://laragon.org/index.html local install just to try to debug the issue. 

Let me know how it goes. 

Cheers

**Comment by webdesign7** [comment]
hey @pxpm  thanks for your replies ! 

I have figured out that I had an old table in my DB  and some columns were using `bit` type , I was completely unaware of those tbh.

So i have changed them to `boolean` and now it works ! 

Issue can be closed now.
