### ISSUE TITLE
Missing "use" in Readme

### ISSUE THREAD

**Issue by webfactor** [Laravel-Backpack/PageManager#22]
Please add

use App\Http\Controllers\Controller;

to the PageController Example. The one displayed results in HTTP 502

**Comment by OwenMelbz** [comment]
Hi @webfactor - If you feel this is needed then by all means submit a PR for review! 

There's a lot of work for 1 person to do, so every little PR with a good explanation helps dramatically

**Comment by tabacitu** [comment]
Done, thank you!
