### ISSUE TITLE
5.4 laravel migrate file not publised

### ISSUE THREAD

**Issue by brazitech** [Laravel-Backpack/PageManager#23]
when following the documentation .. publish does not move the migration file. it has to be copied be hand

**Comment by tabacitu** [comment]
Hmm... just tried it in two different instances and it worked for me:
![screen shot 2017-04-05 at 16 15 48](https://cloud.githubusercontent.com/assets/1032474/24707160/3cbab79c-1a1b-11e7-9b8a-4cd4a5563d90.png)

Closing the issue for now as it seems fixed. If anyone has this problem again, please reply, so we can get to the bottom of this.

Cheers!
