### ISSUE TITLE
Overriding PageRequest - not possible

### ISSUE THREAD

**Issue by njbarrett** [Laravel-Backpack/PageManager#25]
Sorry if I am going crazy but I can't figure this out.

I need to override Backpack\PageManager\app\Http\Requests\PageRequest class

to change the authorize method so that it uses my custom authentication method rather than the standard Illuminate Auth check.

I have created App\Http\Requests\PageRequest but that does not override it.

So I tried to create my own PageCrudController as follows:

```
<?php

namespace App\Http\Controllers\Admin;

use Backpack\PageManager\app\Http\Controllers\Admin\PageCrudController as BackpackPageCrudController;
use App\Http\Requests\PageRequest as StoreRequest;
use App\Http\Requests\PageRequest as UpdateRequest;

class PageCrudController extends BackpackPageCrudController
{
    public function store(StoreRequest $request)
    {
        $this->addDefaultPageFields(\Request::input('template'));
        $this->useTemplate(\Request::input('template'));

        return parent::storeCrud();
    }

    public function update(UpdateRequest $request)
    {
        $this->addDefaultPageFields(\Request::input('template'));
        $this->useTemplate(\Request::input('template'));

        return parent::updateCrud();
    }
}
```

Now I receive:

```
Declaration of App\Http\Controllers\Admin\PageCrudController::store(App\Http\Requests\PageRequest $request) should be compatible with Backpack\PageManager\app\Http\Controllers\Admin\PageCrudController::store(Backpack\PageManager\app\Http\Requests\PageRequest $request)
```

How can I override it with this conflict?

**Comment by tabacitu** [comment]
Huh. That's odd. 

What if you extend from ```App\Http\Requests\PageRequest``` from```Backpack\PageManager\app\Http\Requests\PageRequest```? Does it work then?

Cheers!

**Comment by tabacitu** [comment]
Also, just merged a PR that provides an easy way to use your own Controller or Model. [Check out the instructions here](https://github.com/Laravel-Backpack/PageManager#extend). You'll be able to do that after a ```composer update```.

Cheers!

**Comment by kiddtang** [comment]
@tabacitu The Backpack PermissionManager encounter the same issue. 
Unable to extends CrudRequest Class with this error
`Declaration of App\Http\Controllers\Admin\PermissionCrudController::store(App\Http\Requests\PermissionRequest $request) should be compatible with Backpack\PermissionManager\app\Http\Controllers\PermissionCrudController::store(Backpack\PermissionManager\app\Http\Requests\PermissionCrudRequest $request)`
