### ISSUE TITLE
conflict with SluggableServiceProvide

### ISSUE THREAD

**Issue by c1t1zen** [Laravel-Backpack/PageManager#3]
the newCrud and PageManager package have conflict wiht Sluggable package.
so please fix this .

NewsCrud use a diffirent version for sluggable package

**Comment by tabacitu** [comment]
I'm not getting the same thing. Paste the error please?

**Comment by tabacitu** [comment]
Hi @c1t1zen . 

Is this still a problem? Can I close the issue?

Cheers!

**Comment by c1t1zen** [comment]
you can close i had to change models with the new package
thank you
