### ISSUE TITLE
public function setup() and public function __construct()

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/PageManager#35]
I found that PageCrudController in PageManager uses `public function __construct()` and UserCrudController in PermissionManager uses `public function setup()`. And other controllers also use `public function __construct()`, rather than `public function setup()`.

Are there any differences? Should PageCrudController use `public function setup()`?

**Comment by tabacitu** [comment]
Hi @shinokada ,

They're not _exactly_ the same. ```setup()``` is recommended, as it's loaded after the middleware, so it allows you to do ```Auth::check()``` and things like that. Check out ```CrudController::setup()```:

```php
    public function __construct()
    {
        if (! $this->crud) {
            $this->crud = app()->make(CrudPanel::class);

            // call the setup function inside this closure to also have the request there
            // this way, developers can use things stored in session (auth variables, etc)
            $this->middleware(function ($request, $next) {
                $this->request = $request;
                $this->crud->request = $request;
                $this->setup();

                return $next($request);
            });
        }
    }

    /**
     * Allow developers to set their configuration options for a CrudPanel.
     */
    public function setup()
    {
    }
```

But in PageManager that's rarely the case - I think.

Hope it helps.

Cheers!
