### ISSUE TITLE
Change Routes

### ISSUE THREAD

**Issue by eduardoarandah** [Laravel-Backpack/PageManager#36]
I created a class that extends PageCrudController and set a different route

```
<?php

namespace App\Http\Controllers;

class PageController extends \Backpack\PageManager\app\Http\Controllers\Admin\PageCrudController
{
    public function setup() {
        parent::setup();
        $this->crud->setRoute("XXXXXXXXX");
    }
}

```

Then, in pagemanager.php changed the Controller to use that class

```
<?php

return [
    // Change this class if you wish to extend PageCrudController
    'admin_controller_class' => 'App\Http\Controllers\PageController',

    // Change this class if you wish to extend the Page model
    'page_model_class'       => 'Backpack\PageManager\app\Models\Page',
];

```

Problem is, routes keep the same, only thing that change are the buttons like "Add Page"

`php artisan route:list`

I've seen that routes are hard-coded in setupRoutes()
in:
**vendor\backpack\pagemanager\src\PageManagerServiceProvider.php**
```

    public function setupRoutes(Router $router)
    {
        // Admin Interface Routes
        Route::group(['middleware' => ['web', 'admin'], 'prefix' => config('backpack.base.route_prefix', 'admin')], function () {
            $controller = config('backpack.pagemanager.admin_controller_class', $this->adminControllerClass);

            // Backpack\PageManager routes
            Route::get('page/create/{template}', $controller.'@create');
            Route::get('page/{id}/edit/{template}', $controller.'@edit');

            // This triggered an error before publishing the PageTemplates trait, when calling Route::controller();
            // CRUD::resource('page', $controller . '');

            // So for PageCrudController all routes are explicitly defined:
            Route::get('page/reorder', $controller.'@reorder');
            Route::get('page/reorder/{lang}', $controller.'@reorder');
            Route::post('page/reorder', $controller.'@saveReorder');
            Route::post('page/reorder/{lang}', $controller.'@saveReorder');
            Route::get('page/{id}/details', $controller.'@showDetailsRow');
            Route::get('page/{id}/translate/{lang}', $controller.'@translateItem');
            Route::resource('page', $controller);
        });
    }
```

Shouldn't it use the same route?

How to change the routes?

**Comment by tabacitu** [comment]
Hi @eduardoarandah ,

Unfortunately, I don't think there's a way for us to take the string you've set in the controller, and automatically create routes using it. The routes are registered BEFORE the app reaches the controller. I think the best way for you right now would be to register all the PageManager routes you want, manually. Not a pretty fix, I know...

Since Laravel now supports multiple routes files, I plan on moving those routes to a separate file (```routes/backpack/pagemenager.php```), so it will be a lot easier in the future to change. I'll leave this issue open until then.

Cheers!

**Comment by OliverZiegler** [comment]
As all routes are defined in the new `routes/backpack/pagemanager.php` and one can easily override. This issue can be closed, can't it?

**Comment by lloy0076** [comment]
@OliverZiegler Yes, closing now.
