### ISSUE TITLE
Sharing fields using protected methods

### ISSUE THREAD

**Issue by theycallmepepper** [Laravel-Backpack/PageManager#37]
By default the sample pages are defined as private methods. In the interest of keeping the template definitions organized it would be nice to define "fieldsets", so to speak, as protected methods from inside the private method which defines the page.  This allows for re-use and de-cluttering if you're adding (for example) the same meta fields to several pages types.

Currently, attempting this causes the method created for the fields to show up in the template drop down menu in the admin panel.  If a filter is added to the reflection on trait we can separate these methods.

https://github.com/Laravel-Backpack/PageManager/pull/34

**Comment by lloy0076** [comment]
Closing as #34 claims it is merged.
