### ISSUE TITLE
Adding Fields to Page Manager - Where's the Model / Data?

### ISSUE THREAD

**Issue by lloy0076** [Laravel-Backpack/PageManager#41]
Let's say that I add the following function to `app/PageTemplates.php`:

```
    private function test_me()
    {
        $this->crud->addField([
            'name' => 'testme',
            'label' => 'Test Me',
            'placeholder' => 'Test me placeholder',
        ]);
    }
```

This behaves as **expected**.

However, there are no fields named **testme** in the model so when I enter a value into the text input labelled **Test Me** it's not stored...anywhere!

I then changed the field to:

```
    private function test_me()
    {
        $this->crud->addField([
            'name' => 'testme',
            'label' => 'Test Me',
            'placeholder' => 'Test me placeholder',
            'fake' => true, // Look, pa, we're fake now!
        ]);
    }
```

...and my test was saved.

@tabacitu - this *might* be intended behaviour, however it's somewhat unintuitive to me and probably needs some documentation in the README.md; I'd write the documentation but I don't know what the intended behaviours are meant to be...

**Comment by AbbyJanke** [comment]
@lloy0076 One reason this may be is that you are not defining a `type` within your array. Because the form is trying to find a view to load for that `addField()` and it does not define one by default. Perhaps we need to set a default value for `type` as hidden?

_views.crud.inc.show_fields_
```
@if(view()->exists('vendor.backpack.crud.fields.'.$field['type']))
    @include('vendor.backpack.crud.fields.'.$field['type'], array('field' => $field))
@else
    @include('crud::fields.'.$field['type'], array('field' => $field))
@endif
```

**Comment by tabacitu** [comment]
Hmm... @lloy0076 - yes, that's the intended behaviour. I expected people to usually use fake fields in their template, unless they intend to actually place new column in their DB.

Would this make it clearer?

```diff
USAGE:
1. Go to yourapp/admin/page and see how it works.
-2. Define your own templates in app/PageTemplates.php using the Backpack\CRUD API.
+2. Define your own templates in app/PageTemplates.php using the Backpack\CRUD API. Make sure all the fields you define are [fake fields](https://laravel-backpack.readme.io/docs/advanced-features#section-extras-fake-fields-stored-as-json-in-the-database), so they are stored as JSON in the extras column, unless you actually add a DB column to your table and the $fillable array. 
```

**Comment by lloy0076** [comment]
@tabacitu The above suggestion in https://github.com/Laravel-Backpack/PageManager/issues/41#issuecomment-313101230 would make it clearer (and here I am responding a month afterwards...)

**Comment by lloy0076** [comment]
@tabacitu - I'm going to close this for cleanliness but a doc fix might help :)
