### ISSUE TITLE
Created Page but while opening shows 404

### ISSUE THREAD

**Issue by milanchheda** [Laravel-Backpack/PageManager#43]
Using the admin panel, I created a new page. But when I click on the 'open', it throws 404. What am I missing? 

I created a page named 'About us' with slug URL as 'about-us' and tried various URLs to view the page:
myapp/about-us
myapp/about_us
myapp/page/about-us

But everything throws 404 :(

**Comment by lloy0076** [comment]
Please review the documentation at https://hackaday.io/project/16568-cosmic-array and take note of the heading **No Frontend is Provided**.

This is not really a bug.

**Comment by milanchheda** [comment]
@lloy0076 - Seems you provided a wrong link??

**Comment by lloy0076** [comment]
I meant to the GitHub README for [pagemanager][https://github.com/Laravel-Backpack/PageManager] 😈

**Comment by milanchheda** [comment]
Alright. Got it.
