### ISSUE TITLE
Enable package auto-discovery for faster installation on L5.5

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/PageManager#47]
Enable package auto-discovery for faster installation on L5.5. Eliminate 2-3 steps out of the installation process with a small composer modif:

https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518

**Comment by lloy0076** [comment]
When/if this goes in, PLEASE make it obvious how to **not** register stuff - because one can guarantee someone will ask right away...

**Comment by tabacitu** [comment]
Done!
