### ISSUE TITLE
i cant install using composer coz pagemanger package required an old sluggable version 

### ISSUE THREAD

**Issue by c1t1zen** [Laravel-Backpack/PageManager#5]
Hey !
i cant install using composer coz pagemanger package required an old sluggable version and i have installed base and crud with sluggalbele package without problem but when i try pagemanger it never install at all

any solution ???

thank you in advance

**Comment by tabacitu** [comment]
Hmm... I don't get the same error, can you please copy-paste what you get?

As far as I can see, PageManager is the only package that requires cviebrock/eloquent-sluggable, you shouldn't get any issues. eloquent-sluggable v4.0.0 was pushed 3 days ago, I haven't tested if it works with it yet, but I will soon.

**Comment by c1t1zen** [comment]
hey ,Thank you for reply
look at composer.json for PageManager 
https://github.com/Laravel-Backpack/pagemanager/blob/master/composer.json

    "require": {
        "illuminate/support": "~5.1",
        "php" : "~5.5|~7.0",
        "cviebrock/eloquent-sluggable": "^3.0",
        "backpack/crud": "2.*"
    },

as u see the         "cviebrock/eloquent-sluggable": "^3.0",
works with version 3.0 and that's very old 
when i use following command:
composer require backpack/pagemanager

it never install 

i used this command with crud and base and it use "cviebrock/eloquent-sluggable"
so it make conflict with the installed "cviebrock/eloquent-sluggable"

i had to install PageManager manually (without composer)

note: you may find every package have different version for "cviebrock/eloquent-sluggable"
i had to install "cviebrock/eloquent-sluggable 4.0" and edit model to work with your code

you code is realy nice and i like it i was using grocery crud before and i like your way
but need more documentation for frontend to use
like using pagemanager or how to use category model to get articles

Thank you in advance

**Comment by tabacitu** [comment]
Hi @c1t1zen ,

I've checked all Backpack packages and PageManager is the only one that requires cviebrock/eloquent-sluggable, so I can't see a way for you to have conflicts unless you've required v4 in your app's composer.json

eloquent-sluggable v3.x is not old at all. In fact, v4 has been launched 1 day before you first posted. That being said, of course we'll update to v4 as soon as possible, we just need to check everything's still working if we make the move to v4. That big of a bump usually means API changes and we'll need to adapt to that.

I'll take a look and update next week.

Cheers!

**Comment by tabacitu** [comment]
Still a problem?

**Comment by c1t1zen** [comment]
it's okey i did change model to work with the new version of sluggable package

you may close the issue
