### ISSUE TITLE
Ambiguous class resolution

### ISSUE THREAD

**Issue by nille** [Laravel-Backpack/PageManager#51]
I get this warning message upon installing this package:

Warning: Ambiguous class resolution, "Backpack\Settings\database\seeds\SettingsTableSeeder" was found in both "/home/vagrant/Code/Laravel/vendor/backpack/settings/src/database/seeds/SettingsTableSeeder.php" and "/home/vagrant/Code/Laravel/database/seeds/SettingsTableSeeder.php", the first will be used.

**Comment by lloy0076** [comment]
That's odd - did you follow the general steps (i.e. create a Laravel project, install CRUD, then this?)?

**Comment by en237** [comment]
i have exactly the same issue,  while following steps from https://laravel-backpack.readme.io/docs/install-on-laravel-55

**Comment by packytagliaferro** [comment]
I also got this but not when I installed backpack locally but when I migrated the update using Forge. My forge deployment fails due to it

**Comment by lloy0076** [comment]
I wonder if it's a capitalisation issue.

**Comment by lloy0076** [comment]
Hmmm, so the seeder is being copied over; I'm not sure if they could/should be TBH.

**Comment by lloy0076** [comment]
I think I may see the problem but I'm not sure which package it belongs to.

**Comment by packytagliaferro** [comment]
I just fixed mine in the Settings Package ->` database/seeds/SettingsTableSeeder.php` . 

From 
`namespace Backpack\Settings\database\seeds;`

To:

`namespace backpack\settings\database\seeds;`

**Comment by lloy0076** [comment]
I'm not sure that's the right fix 🎵 it looks like it only "hides" the issue.On 1 Dec 2017 17:07, packytagliaferro <notifications@github.com> wrote:I just fixed mine in the Settings Package ->database/seeds/SettingsTableSeeder.php .
From
namespace Backpack\Settings\database\seeds;
To:
namespace backpack\settings\database\seeds;

**Comment by tabacitu** [comment]
Hi guys - this is definitely one for the settings package. The issue has been since fixed, it was due to using the old syntax for migrations and seeds, not the L5.4 and L5.5 one.

Please reopen the issue if you're still having it.

Cheers!

**Comment by tabacitu** [comment]
Note: for existing projects, you can delete the settings seed file manually - you don't actually NEED it, it's just there to provide some examples:

```
rm database/seeds/SettingsTableSeeder.php
```

This should prevent your notice.
