### ISSUE TITLE
Page content is not saved

### ISSUE THREAD

**Issue by nielvrom** [Laravel-Backpack/PageManager#54]
I've added a new function contact in the file *PageTemplates.php* like this:

```
private function contact()
    {
        $this->crud->addField([
            'name' => 'adres',
            'label' => 'Adres',
            'type' => 'address',
            'placeholder' => 'Oudstrijdersstraat 37, 8770 Ingelmunster',
            'store_as_json' => true
        ]);

        $this->crud->addField([
            'name' => 'telehpone',
            'label' => 'Telefoon',
            'type' => 'text',
            'placeholder' => '051/30 28 44',
            'store_in' => 'extras',
        ]);

        $this->crud->addField([
            'name' => 'email',
            'label' => 'Email',
            'type' => 'email',
            'placeholder' => 'plakwerkendemasure@skynet.be',
            'store_in' => 'extras',
        ]);
    }
```

But when I fill in the form and save the data my custom fields (that I've added in my function) are not saved.

<img width="817" alt="schermafbeelding 2017-10-27 om 14 09 04" src="https://user-images.githubusercontent.com/2797731/32103392-7559fb98-bb20-11e7-9c76-28161447c9db.png">

**Comment by zschuessler** [comment]
Is your attribute fillable on the model? Make sure it's in the $fillable array or not guarded.

**Comment by nielvrom** [comment]
I don't have a model for Page. It's also not defined in the documentation.

**Comment by lloy0076** [comment]
The idea, I think, is to add all the extra fields as fake fields.

@tabacitu - is this right - I've never quite figured out how to use the page manager module properly?

**Comment by nielvrom** [comment]
This worked with fake fields.
