### ISSUE TITLE
Fake Fields Cannot Retrieve Data Back

### ISSUE THREAD

**Issue by hackshade-techs** [Laravel-Backpack/PageManager#56]
# Bug report

**Comment by greylegface** [comment]
I am also seeing this behaviour.

Installed backpack with pagemanager, opened a new file, one of the defaults and insert some data. Data is saved to the database under the fake fields, but it isn't being populated in the input fields. 

I thought I may have done something wrong on install, so I pulled a previous commit and reinstalled backpack, with the same result. 

I have done some digging and I have found that the getUpdateFields() on Backpack\CRUD\PanelTraits Update.php isn't returning the values for the fields

`foreach ($fields as $k => $field) {
            // set the value
            if (! isset($fields[$k]['value'])) {
                if (isset($field['subfields'])) {
                    $fields[$k]['value'] = [];
                    foreach ($field['subfields'] as $key => $subfield) {
                        $fields[$k]['value'][] = $entry->{$subfield['name']};
                    }
                } else {
                    $fields[$k]['value'] = $entry->{$field['name']};
                }
            }
        }`

$fields[$k]['value'][] = $entry->{$subfield['name']}; is returning 'null'

**Comment by hojjabr** [comment]
Same problem, any solution? values are returned as null.

**Comment by adriandmitroca** [comment]
I am experiencing the same issue. Seems like PageManager is not saving extras at all with the latest version of Backpack's Base & CRUD.

**Comment by adriandmitroca** [comment]
Guys, here's the fix:

https://github.com/Laravel-Backpack/CRUD/pull/1156

For a temporary fix without making own forks, you can use your own `Page` model and override `addFakes` method there.

**Comment by tabacitu** [comment]
Fixed! Thank you @adriandmitroca ! Sorry guys.
