### ISSUE TITLE
How to change the pagination size 

### ISSUE THREAD

**Issue by michapixel** [Laravel-Backpack/PageManager#6]

**Comment by tabacitu** [comment]
Hi @michapixel ,

A. The easiest way would be to change the ```default_page_length``` in your ```config/backpack/crud.php```. This would change it for all of your CRUDs.

B. If you only want it for the PageManager, you're going to need to:
- make a new controller that extends Backpack's PageCrudController and use ```$this->crud->setDefaultPageLength(10);``` in the constructor;
- redo [all the PageManager routes](https://github.com/Laravel-Backpack/PageManager/blob/master/src/PageManagerServiceProvider.php#L41-L60) in your routes.php file, to point to the new controller;

Hope this helps.

Cheers!

**Comment by michapixel** [comment]
Thanks, i'm just working on a colleagues project because deadline. i dunno how he installed Backpack/Pagemanager but i have no file "config/backpack/crud.php" :-(
since i don't need pagination (if you use pagination @least set focus on the searchfield! :-) ) i just edited 
list.blade.php and added a paging: false to the DataTable-script. (line 167)

**Comment by michapixel** [comment]
but thanks for answering so fast. it's good to know there are other ways.

**Comment by michapixel** [comment]
Oh, and i'm sorry i can't test your suggestions here. Maybe i try to go route 2, just to give sth back to your project here, which is great!
