### ISSUE TITLE
Can't upload images

### ISSUE THREAD

**Issue by augustpemberton** [Laravel-Backpack/PageManager#66]
I'm trying to edit the page form so I can upload an image with the post, however I can't get anything stored as a file or get the path stored in the database.

In PageTemplates.php: 
```
$this->crud->addField([ 
            'name' => 'image',
            'label' => 'Photo',
            'type' => 'upload',
            'upload' => true,
            'fake' => true
        ]);
```
In Page.php:
```
public function setImageAttribute($value)
    {
    	Log::info('New Image upload:');
        Log::alert(json_encode($value));
        $attribute_name = "image";
        if (request()->hasFile($attribute_name) && request()->file($attribute_name)->isValid()) {
            throw new \Exception('xxxIT SHOULD WORK'); 
        }

        $disk = "public";
        $destination_path = "/uploads";       
        $this->uploadFileToDisk($value, $attribute_name, $disk, $destination_path);
    }
```
The log alert returns an empty array, so the image isn't even getting to the setImageAttribute function.

Any help would be greatly appreciated thanks!

**Comment by tabacitu** [comment]
Hi @augustpemberton ,

Sorry to be so late to reply. Have you figured out what your problem was? Your solution could help others that run into the same problem.

Cheers!
