### ISSUE TITLE
I have fix, but can`t push it

### ISSUE THREAD

**Issue by VTumanov** [Laravel-Backpack/PageManager#67]
# Bug report
When enable revisions to PageManager, it not resolve revisions URI`s 
Like this one - http://127.0.0.1:8000/admin/page/2/revisions
Server returns 404 error

### What I did:
Fix by add revision routes to PageManager, but i can`t make git push to this repo.

### What I've already tried to fix it:
Please add this two strings to /pagemanager/src/routes/backpack/pagemanager.php

Route::get('page/{id}/revisions', $controller.'@listRevisions');
Route::post('page/{id}/revisions/{revisionId}/restore', $controller.'@restoreRevision');

**Comment by tabacitu** [comment]
Hi @VTumanov ,

I'm afraid revisions is not supported by default by this package. Some developers might need it, others might not. If you want revisions on Pages, I recommend you [extend the package](https://github.com/Laravel-Backpack/PageManager#extend) or just copy-paste the controllers, model and request into your own app and change the namespaces - that would work too.

Cheers!
