### ISSUE TITLE
Change existing template

### ISSUE THREAD

**Issue by Lider07** [Laravel-Backpack/PageManager#68]
# Bug report

### What I did:
Click edit button and after that change template
### What I expected to happen:
Change fields
### What happened:
404 not found
### Problem
Method public function getCurrentEntryId() in Backpack\CRUD\PanelTraits\Read return template type

### Backpack, Laravel, PHP, DB version:
Backpack 3.4? Laravel 5.6, PHP 7.2

**Comment by g87andres** [comment]
This worked for me:

```
// Overwrites the CrudController edit() method to add template usage.
    public function edit($id)
    {
        $template = request('template');
        // // if the template in the GET parameter is missing, figure it out from the db
        if ($template == null) {
            $model = $this->crud->model;
            $this->data['entry'] = $model::findOrFail($id);
            $template = $this->data['entry']->template;
        }
        $this->addDefaultPageFields($template);
        $this->useTemplate($template);

        return parent::edit($id);
    }
```

**Comment by tabacitu** [comment]
You're totally right @Lider07 and @g87andres - that's the expected behaviour, and that's how it used to work, no idea when this got broken.

@g87andres thanks for the fix, I just pushed your code into ```master``` now, a ```composer update``` and asset republishing should fix it for everyone.

Thanks again, cheers!
