### ISSUE TITLE
Add screenshots to readme

### ISSUE THREAD

**Issue by ian-p** [Laravel-Backpack/PageManager#69]
Not a bug report but a feature request: 

I suggest adding one or two screenshots of the package in work in readme.md. Since there's on live demo available before following the install instructions it would make sense to have at least a peek of what this package offers in terms of functionality.

**Comment by tabacitu** [comment]
You're totally right. Thank you @ian-p , just added an image to the Readme - I also hate it when there are no screenshots there.

Cheers!
