### ISSUE TITLE
Change service provider in documentation

### ISSUE THREAD

**Issue by slozano95** [Laravel-Backpack/PageManager#7]
Hi
It was
Cviebrock\EloquentSluggable\SluggableServiceProvider::class,
Backpack\PageManager\PageManagerServiceProvider::class,

It should be 

Cviebrock\EloquentSluggable\ServiceProvider::class,
Backpack\PageManager\PageManagerServiceProvider::class,

**Comment by tabacitu** [comment]
Yup, you're right @slozano95 . Must have missed that. Done, thank you!
