### ISSUE TITLE
Edit page content found 404 when I changed template

### ISSUE THREAD

**Issue by gumpon** [Laravel-Backpack/PageManager#72]
found 404 page when I changed service to about_us template.

404
Page not found.

No query results for model [Backpack\PageManager\app\Models\Page] about_us

**Comment by tabacitu** [comment]
Hi @gumpon ,

Seems to work for me https://cl.ly/e491f7f05d3c

1) How did you install PageManager?
2) Did you change it in any way?

Cheers!

**Comment by gumpon** [comment]
1. README.md 
install step by step 

2. not change

PS.  I user laravel 5.6.13 and PHP 7.1.8

**Comment by tabacitu** [comment]
That’s odd.

1. What’s your initial URL?
2. What’s the URL you’re redirected to?
3. Do you have a way to record your screen while this happens - might help debugging.

**Comment by gumpon** [comment]
Developed on localhost:8000 . I have record my screen here http://danbkk.com/temp/404.gif

**Comment by tabacitu** [comment]
Hi @gumpon ,

Looks like after you select a different template you’re being redirected to
```admin/page/1/edit/about_us```
but you should be redirected to
```admin/page/1/edit?template=about_us```

I’m pretty sure you have an old version of the template field. Please [put this file](https://github.com/Laravel-Backpack/PageManager/blob/master/src/resources/views/vendor/backpack/crud/fields/select_page_template.blade.php) in your ```resources/views/vendor/backpack/crud/fields/select_page_template.blade.php``` - overwrite the file if it already exists.

That should fix it for you.

Cheers!
