### ISSUE TITLE
display fakefields in view?

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/PageManager#8]
Hi,
im creating a master layout and i would like to display the metas in the head..for the title im using {{$title}} and it works..
{{$page->title}} also works.. because title is in its own column.. but what about the extras column?
when i use `{{$page -> extras}}` i get `{"meta_title":"services","meta_description":"services","meta_keywords":"services"}` as an echo but how do i select which of the above to show?
ive tried using dot annotation like `{{$page->extras.meta_title}}`, and `{{$page->extras->meta_title}}`, and `{{$page->extras[meta_title]}}` but none of them work..
how can i pass these values separately in the view?
any pointer would be great.. thanks.

**Comment by tabacitu** [comment]
Hi @mpixelz ,

You should get the 'extras' as attributes on ```$page```.  Does ```$page->meta_title``` not work? If not, can you please do a ```dd($page);``` and show me the results?

Cheers!

**Comment by mpixelz** [comment]
yeah that worked.. i didnt know it was fetching those values separately as well.. and didnt know about the dd($page) trick either 😄  
things would be much easier now 😄  thanks alot! im falling in love with laravel and specially backpack 💃

**Comment by tabacitu** [comment]
:-) great to hear that. Cheers!
