### ISSUE TITLE
page_or_link field type doesn't save second parameter

### ISSUE THREAD

**Issue by emilushi** [Laravel-Backpack/PageManager#83]
# Bug report

### What I did:
I created a new template on PageTemplates with my own custom fields and one of the field is `page_or_link`. Below is the code for this custom field:

    $this->crud->addField([
        'name'       => 'hero_button_link',
        'label'      => 'Button Url',
        'type'       => 'page_or_link',
        'fake'       => true,
        'store_in'   => 'extras',
        'page_model' => Page::class,
        'tab'        => 'Hero'
    ]);

### What I expected to happen:
I was expecting it be saved as JSON array with two properties like: link type and the link something like:

    {
        "hero_button_link" : [
            {"type": "page_link", "link": "about-us"}
        ],
    }

### What happened:
Instead of what i expected the field was saved only with the first parameter like below:

    {
        "hero_button_link" : "page_link"
    }

### What I've already tried to fix it:
I haven't yet investigated it :( but hopping to have time and investigate on it.

### Backpack, Laravel, PHP, DB version:
Below is a part of my `composer.json`

    "require": {
        "php": "^7.1.3",
        "backpack/base": "^1.1.4",
        "backpack/crud": "^3.6.16",
        "backpack/logmanager": "^2.3.25",
        "backpack/menucrud": "^1.0.13",
        "backpack/newscrud": "^2.1.10",
        "backpack/pagemanager": "^1.1.28",
        "backpack/permissionmanager": "^4.0.4",
        "backpack/settings": "^2.1.3",
        "barryvdh/laravel-elfinder": "^0.4.2",
    }

BD version: `8.0.16 (Homebrew)`
Laravel Framework 5.8.15

**Note: I don't know if this is a PageManager issue or a Backpack issue. I will look at it and confirm...**

**Comment by promatik** [comment]
@emilushi thank you for your report, I created a PR for this issue, I hope we can merge it soon. 
I believe we can now move the conversation to https://github.com/Laravel-Backpack/CRUD/pull/3315

**Comment by tabacitu** [comment]
@promatik what's the update on this? You tested and it was working properly, right? You couldn't confirm @emilushi 's problem?

**Comment by promatik** [comment]
Yes, the problem here was @emilushi wasn't using the correct field initialization;

```php
$this->crud->addField([
    'name'       => 'hero_button_link',
    ...
```

instead of;
```php
$this->crud->addField([
    'name'       => ['type', 'link', 'page_id'],
    ...
```

[Docs for `page_or_link` field](https://backpackforlaravel.com/docs/4.1/crud-fields#page_or_link).

At first I confirmed the issue because I copy pasted the code.
@emilushi the issue is pretty old, but if you still have any problem, feel free reopen.

**Comment by tabacitu** [comment]
Oh right! Got, thanks @promatik . I'm sure being explicit about the solution will help someone who stumbles upon this, someday 😄 Thanks!
