### ISSUE TITLE
Not installing with Laravel 6

### ISSUE THREAD

**Issue by brynnb** [Laravel-Backpack/PageManager#86]
# Bug report

### What I did: 

Installed fresh Laravel 6 app, then tried to install PageManager

### What I expected to happen:

PageManager installs

### What happened:

$ composer require backpack/pagemanager
Using version ^1.1 for backpack/pagemanager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install backpack/pagemanager 1.1.28
    - Conclusion: don't install backpack/pagemanager 1.1.27
    - Conclusion: don't install backpack/pagemanager 1.1.26
    - Conclusion: don't install backpack/pagemanager 1.1.25
    - Conclusion: don't install backpack/pagemanager 1.1.23
    - Conclusion: don't install backpack/pagemanager 1.1.22
    - Conclusion: don't install backpack/pagemanager 1.1.21
    - Conclusion: don't install backpack/pagemanager 1.1.20
    - Conclusion: don't install backpack/pagemanager 1.1.19
    - Conclusion: don't install backpack/pagemanager 1.1.18
    - Conclusion: don't install backpack/pagemanager 1.1.17
    - Conclusion: don't install backpack/pagemanager 1.1.10
    - Conclusion: don't install backpack/pagemanager 1.1.9
    - Conclusion: don't install backpack/pagemanager 1.1.8
    - Conclusion: don't install backpack/pagemanager 1.1.6
    - Conclusion: don't install backpack/pagemanager 1.1.5
    - Conclusion: don't install backpack/pagemanager 1.1.4
    - Conclusion: don't install backpack/pagemanager 1.1.3
    - Conclusion: don't install backpack/pagemanager 1.1.2
    - Conclusion: don't install backpack/pagemanager 1.1.1
    - Conclusion: remove laravel/framework v6.0.0
    - Installation request for backpack/pagemanager ^1.1 -> satisfiable by backp                                                                                                                                                                                               ack/pagemanager[1.1, 1.1.1, 1.1.10, 1.1.17, 1.1.18, 1.1.19, 1.1.2, 1.1.20, 1.1.2                                                                                                                                                                                               1, 1.1.22, 1.1.23, 1.1.25, 1.1.26, 1.1.27, 1.1.28, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1                                                                                                                                                                                               .1.8, 1.1.9].
    - Conclusion: don't install laravel/framework v6.0.0
    - backpack/pagemanager 1.1 requires illuminate/support ~5.1 -> satisfiable b                                                                                                                                                                                               y laravel/framework[5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x                                                                                                                                                                                               -dev, 5.8.x-dev], illuminate/support[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev,                                                                                                                                                                                                5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.1.1, v5.                                                                                                                                                                                               1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.                                                                                                                                                                                               1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.                                                                                                                                                                                               27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0                                                                                                                                                                                               , v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36,                                                                                                                                                                                                v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v                                                                                                                                                                                               5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5                                                                                                                                                                                               .6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v                                                                                                                                                                                               5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v                                                                                                                                                                                               5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v                                                                                                                                                                                               5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.                                                                                                                                                                                               9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22,                                                                                                                                                                                                v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.                                                                                                                                                                                               7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.                                                                                                                                                                                               19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.3                                                                                                                                                                                               0, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.4, v5.8.8, v5.8.9].
    - Can only install one of: laravel/framework[5.5.x-dev, v6.0.0].
    - Can only install one of: laravel/framework[5.6.x-dev, v6.0.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v6.0.0].
    - Can only install one of: laravel/framework[5.8.x-dev, v6.0.0].
    - illuminate/support 5.2.x-dev conflicts with laravel/framework[v6.0.0].
    - illuminate/support 5.3.x-dev conflicts with laravel/framework[v6.0.0].
    - illuminate/support 5.4.x-dev conflicts with laravel/framework[v6.0.0].
    - illuminate/support 5.5.x-dev conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.2.43 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.2.45 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.3.0 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.3.16 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.3.23 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.3.4 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.4.0 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.4.13 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.4.17 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.4.19 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.4.27 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.4.36 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.4.9 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.5.0 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.5.16 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.5.17 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.5.2 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.5.28 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.5.35 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.5.36 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.5.37 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.5.39 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.5.40 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.5.41 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.5.43 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.5.44 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.6.4 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.6.5 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.6.6 conflicts with laravel/framework[v6.0.0].
    - illuminate/support v5.6.7 conflicts with laravel/framework[v6.0.0].
    - laravel/framework 5.2.x-dev conflicts with laravel/framework[v6.0.0].
    - laravel/framework 5.3.x-dev conflicts with laravel/framework[v6.0.0].
    - laravel/framework 5.4.x-dev conflicts with laravel/framework[v6.0.0].
    - don't install illuminate/support v5.5.33|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.5.34|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support 5.6.x-dev|don't install laravel/framework                                                                                                                                                                                                v6.0.0
    - don't install illuminate/support v5.6.0|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.6.1|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.6.10|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.11|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.12|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.13|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.14|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.15|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.16|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.17|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.19|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.2|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.6.20|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.21|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.22|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.23|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.24|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.25|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.26|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.27|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.28|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.29|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.3|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.6.30|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.31|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.32|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.33|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.34|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.35|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.36|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.37|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.38|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.39|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.6.8|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.6.9|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support 5.7.17|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support 5.7.18|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support 5.7.19|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support 5.7.x-dev|don't install laravel/framework                                                                                                                                                                                                v6.0.0
    - don't install illuminate/support v5.7.0|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.7.1|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.7.10|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.7.11|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.7.15|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.7.2|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.7.20|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.7.21|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.7.22|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.7.23|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.7.26|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.7.27|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.7.28|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.7.3|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.7.4|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.7.5|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.7.6|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.7.7|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.7.8|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.7.9|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework                                                                                                                                                                                                v6.0.0
    - don't install illuminate/support v5.8.0|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.8.11|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.12|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.14|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.15|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.17|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.18|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.19|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.2|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.8.20|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.22|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.24|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.27|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.28|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.29|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.3|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.8.30|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.31|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.32|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.33|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.34|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.8.4|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.8.8|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.8.9|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support 5.1.x-dev|don't install laravel/framework                                                                                                                                                                                                v6.0.0
    - don't install illuminate/support v5.1.1|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.1.13|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.1.16|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.1.2|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.1.20|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.1.22|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.1.25|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.1.28|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.1.30|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.1.31|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.1.41|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.1.6|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.1.8|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.2.0|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.2.19|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.2.21|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.2.24|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.2.25|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.2.26|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.2.27|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.2.28|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.2.31|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.2.32|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.2.37|don't install laravel/framework v                                                                                                                                                                                               6.0.0
    - don't install illuminate/support v5.2.6|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - don't install illuminate/support v5.2.7|don't install laravel/framework v6                                                                                                                                                                                               .0.0
    - Installation request for laravel/framework (locked at v6.0.0, required as                                                                                                                                                                                                ^6.0) -> satisfiable by laravel/framework[v6.0.0].

Installation failed, reverting ./composer.json to its original content.

### What I've already tried to fix it:

Don't have time today to look into fix, but thought I would try to be helpful by opening issue

### Backpack, Laravel, PHP, DB version:

Laravel 6
PHP 7.2.3

**Comment by tabacitu** [comment]
Indeed, Laravel 6 support wasn't added yet. I've added it today. You can try again, it should work this time.

Cheers!
