### ISSUE TITLE
how to create page template for new Model

### ISSUE THREAD

**Issue by zunky44** [Laravel-Backpack/PageManager#9]
I have categories and Products Models. I need to display products by categories and individual products details. But i am not getting any ideas how to display them in custom templates (frontend).

**Comment by tabacitu** [comment]
Hi @zunky44 ,

If it were me, I'd create 3 admin panels. Their controllers would be:
- CategoryCrudController
- ProductCrudController
- CategoryProductCrudController, that extends ProductCrudController but adds a ```$this->crud->addClause('where', 'category_id', '==', $category_id); ```; Then this panel would show only one category's products; You can see [instructions of how that's done here](https://github.com/Laravel-Backpack/CRUD/issues/82#issuecomment-246306789); You can allow a user to go here by adding a [custom button](https://laravel-backpack.readme.io/docs/crud-buttons#button-functions) next to each category in your Category panel; 

Would this work for you?

Cheers!
