### ISSUE TITLE
Not installing Laravel 5.8

### ISSUE THREAD

**Issue by hermesalvesbr** [Laravel-Backpack/PageManager#98]
# Bug report
 composer require backpack/pagemanager
Using version ^2.0 for backpack/pagemanager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install backpack/pagemanager 2.0.2
    - Conclusion: don't install backpack/pagemanager 2.0.1
    - Conclusion: remove laravel/framework v5.8.35
    - Installation request for backpack/pagemanager ^2.0 -> satisfiable by backpack/pagemanager[2.0.0, 2.0.1, 2.0.2].
    - Conclusion: don't install laravel/framework v5.8.35
    - backpack/pagemanager 2.0.0 requires cviebrock/eloquent-sluggable ^6.0 -> satisfiable by cviebrock/eloquent-sluggable[6.0.0, 6.0.1, 6.0.2].
    - cviebrock/eloquent-sluggable 6.0.1 requires illuminate/support ^6.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0].
    - cviebrock/eloquent-sluggable 6.0.2 requires illuminate/support ^6.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0].
    - cviebrock/eloquent-sluggable 6.0.0 requires illuminate/database ~6.0.0 -> satisfiable by illuminate/database[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
    - Can only install one of: laravel/framework[6.x-dev, v5.8.35].
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.0.0|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.0.1|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.0.2|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.0.3|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.0.4|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.1.0|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.2.0|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.3.0|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.4.1|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.5.0|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.5.1|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.5.2|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.6.0|don't install laravel/framework v5.8.35
    - don't install illuminate/database v6.0.0|don't install laravel/framework v5.8.35
    - don't install illuminate/database v6.0.1|don't install laravel/framework v5.8.35
    - don't install illuminate/database v6.0.2|don't install laravel/framework v5.8.35
    - don't install illuminate/database v6.0.3|don't install laravel/framework v5.8.35
    - don't install illuminate/database v6.0.4|don't install laravel/framework v5.8.35
    - Installation request for laravel/framework (locked at v5.8.35, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.35].

Installation failed, reverting ./composer.json to its original content.

### What I did:
 composer require backpack/pagemanager

### Backpack, Laravel, PHP, DB version:
 php -v
PHP 7.3.11 (cli) (built: Oct 24 2019 11:29:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11, Copyright (c) 1999-2018, by Zend Technologies

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "backpack/backupmanager": "^2.0",
        "backpack/crud": "^4.0",
        "backpack/logmanager": "^3.0",
        "backpack/permissionmanager": "^5.0",
        "backpack/settings": "^3.0",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "backpack/generators": "^2.0",
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "laracasts/generators": "^1.1",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

**Comment by tabacitu** [comment]
Hi @hermesalvesbr ,

Sorry for taking so long to take care of this. Looks like the same problem as here - https://github.com/Laravel-Backpack/NewsCRUD/issues/39 - caused by ```cviebrock/eloquent-sluggable```. So the fix should be the same.

I've just pushed the fix to allow you to install this package on Laravel 5.8 & Backpack v4 too. It's available as version 2.0.3.

Cheers!
